print("  |========CALCULADORA========|\n"
      "A)|ADIÇÃO                     |\n"
      "B)|MULTIPLICAÇÃO              |\n"
      "C)|POTENCIAÇÃO                |\n"
      "D)|SUBTRAÇÃO                  |\n"
      "E)|DIVISÃO INT                |\n"
      "F)|DIVISÃO NÃO INT            |\n"
      "G)|TABUADA                    |\n"
      "  |=====TRIGONOMETRIA=========|\n"
      "A)|CALCULO DE HIPOTENUSA      |\n"
      "B)|CALCULO DE CATETO ADJACENTE|\n"
      "C)|CALCULO DE CATETO OPOSTO   |\n"
      "K)|      ----EXIT---->        |")